In [31]:
import torch
import torch.nn as nn

In [32]:
X = torch.tensor([
    [40.2],
    [10.3],
    [13.4],
    [10.1]], dtype=torch.float32)
y = torch.tensor([
    [20.1],
    [4.2],
    [1.2],
    [20.4]], dtype=torch.float32)

In [33]:
model = nn.Linear(1,1)
model

Linear(in_features=1, out_features=1, bias=True)

In [34]:
loss_fn = torch.nn.MSELoss()

In [35]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.001)


In [36]:
for i in range(0, 10000):
  optimizer.zero_grad()
  outputs = model(X)
  loss = loss_fn(outputs, y)
  loss.backward()
  optimizer.step()

  if i % 1000 == 0:
    print(f"Epoch: {i}, Loss: {loss.item()} Weight: {model.weight} Bias: {model.bias}")


Epoch: 0, Loss: 149.52456665039062 Weight: Parameter containing:
tensor([[0.5706]], requires_grad=True) Bias: Parameter containing:
tensor([-0.9073], requires_grad=True)
Epoch: 1000, Loss: 61.38612365722656 Weight: Parameter containing:
tensor([[0.4680]], requires_grad=True) Bias: Parameter containing:
tensor([1.8340], requires_grad=True)
Epoch: 2000, Loss: 59.19125747680664 Weight: Parameter containing:
tensor([[0.4142]], requires_grad=True) Bias: Parameter containing:
tensor([3.2899], requires_grad=True)
Epoch: 3000, Loss: 58.572235107421875 Weight: Parameter containing:
tensor([[0.3857]], requires_grad=True) Bias: Parameter containing:
tensor([4.0630], requires_grad=True)
Epoch: 4000, Loss: 58.397647857666016 Weight: Parameter containing:
tensor([[0.3705]], requires_grad=True) Bias: Parameter containing:
tensor([4.4736], requires_grad=True)
Epoch: 5000, Loss: 58.34840393066406 Weight: Parameter containing:
tensor([[0.3624]], requires_grad=True) Bias: Parameter containing:
tensor([4.

In [37]:
m = torch.tensor([
    [10.3]
    ], dtype=torch.float32)

In [38]:
model.eval()

Linear(in_features=1, out_features=1, bias=True)

In [39]:
with torch.no_grad():
  prediction= model(m)
  print(prediction)

tensor([[8.5713]])
